from nes_py.wrappers import JoypadSpace
import gym_super_mario_bros
from gym_super_mario_bros.actions import RIGHT_ONLY

from movement import right, right_jump

def play_11(env):
    right(env, 90)
    right_jump(env, 10)
    right(env, 20)
    right_jump(env, 10)
    right(env, 50)
    right_jump(env, 10)
    right(env, 15)
    right_jump(env, 20)
    right(env, 29)
    right_jump(env, 50)
    right(env, 50)
    right_jump(env, 5)
    right(env, 90)
    right_jump(env, 5)
    right(env, 50)
    right_jump(env, 5)
    right(env, 40)
    right_jump(env, 5)
    right(env, 55)
    right_jump(env, 5)
    right(env, 50)
    right_jump(env, 10)
    right(env, 40)
    right_jump(env, 20)
    right(env, 15)
    right_jump(env, 5)
    right(env, 35)
    right_jump(env, 20)
    right(env, 15)
    right_jump(env, 5)
    right(env, 45)
    right_jump(env, 5)
    right(env, 50)
    right_jump(env, 5)
    right(env, 25)
    right_jump(env, 5)
    right(env, 20)
    right_jump(env, 5)
    right(env, 20)
    right_jump(env, 5)
    right(env, 20)
    right_jump(env, 5)
    right(env, 20)
    right_jump(env, 5)
    right(env, 20)
    right_jump(env, 5)
    right(env, 25)
    right_jump(env, 50)

env = gym_super_mario_bros.make("SuperMarioBros-v0")
env = JoypadSpace(env, RIGHT_ONLY)
env.reset()
play_11(env)
env.close()
